### PR TITLE
Add proposal id param to pagination

### PR DESCRIPTION
**Pull request by ChaituVR**

### CODE REVIEW

**Comment by bonustrack** [comment]
@ChaituVR Why proposal id? I'd rather show the space, this is more explicit. The pagination is not specific to a proposal but a strategy. You can change pagination.json to pagination.ts with export default and add space id as comment

**Comment by ChaituVR** [comment]
@bonustrack We can't retrieve strategies for a particular space if the settings are changed right? we can get space name from the proposal,

The idea is, in case we want to know which strategies belong to the hash, we can easily retrieve from the proposal, but not space (because it can change anytime and there is a chance that old/open proposals still fail)? 🤔

**Comment by ChaituVR** [comment]
@bonustrack Added both space and proposal in comments

**Review by bonustrack — APPROVED** [review]
Looks good

**Pull request merged**
